language: java
//install: skip

dist: trusty

jdk:
  - oraclejdk8

  
sudo: false

addons:
  apt:
    packages:
      - oracle-java8-installer

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  
  
script:
  - ./gradlew build
  - ./gradlew test
  - ./gradlew clean build jacocoTestReportDebug


################ CODE CLIMATE #########################

env:
  global:
    CC_TEST_REPORTER_ID= $CC_TEST_REPORTER_ID
    JACOCO_SOURCE_PATH=src/main/java ./cc-test-reporter format-coverage ./build/reports/jacoco/test/jacocoTestReport.xml --input-type jacoco

after_script:
  - ./cc-test-reporter upload-coverage $CC_TEST_REPORTER_ID
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT


//before_install:                       



# Pipe the coverage data to Code Climate
/*after_script:
  - ./cc-test-reporter format-coverage -t simplecov -o coverage/codeclimate.backend.json coverage/backend/.resultset.json # Format backend coverage
  - ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.frontend.json coverage/frontend/lcov.info  # Format frontend coverage
  - ./cc-test-reporter sum-coverage coverage/codeclimate.*.json -p 2                  # Sum both coverage parts into coverage/codeclimate.json
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage; fi  # Upload coverage/codeclimate.json
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
*/
/*after_success:
  - ./cc-test-reporter upload-coverage -r $CC_TEST_REPORTER_ID

 # Cache gems
cache:
  bundler: true
  directories:
    - node_modules

addons:
  chrome: stable
  #firefox: latest

after_success:
  - bash <(curl -s https://codecov.io/bash)
  */
